VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes

KEY_LOCK_ENABLE = yes
MOUSEKEY_ENABLE = yes
LTO_ENABLE = yes

# debug
# NKRO_ENABLE = no
# MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
# CONSOLE_ENABLE = yes
